name: Build and Publish Docker image

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*', 'release-*' ]
    paths:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: dunczyk/pdfcompressor

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main') }}
            type=ref,event=tag
            type=sha,format=short

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}


