name: Build macOS DMG

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'electron/**'
      - 'src/**'
      - 'package.json'
      - 'webpack*.js'
      - '.github/workflows/release-macos.yml'

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      - name: Build macOS DMG (unsigned)
        run: npx electron-builder -m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist/*.dmg

      - name: Determine version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release (draft, macOS)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}-${{ github.run_number }}-mac
          name: PDF Compressor v${{ env.VERSION }} (macOS build ${{ github.run_number }})
          draft: true
          prerelease: true
          files: |
            dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
