name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'electron/**'
      - 'src/**'
      - 'package.json'
      - 'webpack*.js'
      - '.github/workflows/release-windows.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      - name: Build Windows NSIS + Portable + ZIP
        run: npx electron-builder --win nsis portable zip --x64

      - name: Upload installer artifact (NSIS)
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe

      - name: Upload portable artifact (exe)
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-exe
          path: dist/*-portable.exe

      - name: Upload portable artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-zip
          path: dist/*.zip

